# Generated by CMake 3.0.0

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget kangaroo)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target kangaroo
add_library(kangaroo SHARED IMPORTED)

# Import target "kangaroo" for configuration "Release"
set_property(TARGET kangaroo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(kangaroo PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/local/cuda/lib/libcudart.dylib;-Wl,-rpath;-Wl,/usr/local/cuda/lib;/usr/local/cuda/lib/libnpp.dylib;/opt/local/lib/libassimp.dylib;/usr/local/lib/libopencv_core.dylib;/usr/local/lib/libopencv_imgproc.dylib;/usr/local/lib/libopencv_features2d.dylib;/usr/local/lib/libopencv_flann.dylib;/usr/local/lib/libopencv_calib3d.dylib;/usr/local/lib/libopencv_objdetect.dylib;/usr/local/lib/libopencv_legacy.dylib;/usr/local/lib/libopencv_contrib.dylib;/usr/local/lib/libopencv_highgui.dylib;/usr/local/lib/libopencv_ml.dylib;/usr/local/lib/libopencv_video.dylib;/usr/local/lib/libopencv_gpu.dylib"
  IMPORTED_LOCATION_RELEASE "/Users/luma/Code/RobotGroup/MKangaroo/kangaroo/libkangaroo.dylib"
  IMPORTED_SONAME_RELEASE "/Users/luma/Code/RobotGroup/MKangaroo/kangaroo/libkangaroo.dylib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
